apiVersion: apps/v1
kind: Deployment
metadata:
  name: decoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decoder
  template:
    metadata:
      labels:
        app: decoder
    spec:
      containers:
      - name: decoder
        image: sheykh8/tacotron_decoder:latest
        resources:
          requests:
            cpu: "4000m"
          limits:
            memory: "1500Mi"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
