apiVersion: apps/v1
kind: Deployment
metadata:
  name: decoder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: decoder
  template:
    metadata:
      labels:
        app: decoder
    spec:
      containers:
      - name: decoder
        image: sheykh8/tacotron_decoder:latest
        ports:
        - containerPort: 80
