apiVersion: apps/v1
kind: Deployment
metadata:
  name: encoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: encoder
  template:
    metadata:
      labels:
        app: encoder
    spec:
      containers:
      - name: encoder
        image: sheykh8/tacotron_encoder:latest
        resources:
          requests:
            cpu: "200m"
          limits:
            memory: "600Mi"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
