apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: sheykh8/tacotron_orchestrator:latest
        resources:
          requests:
            cpu: "300m"
          limits:
            memory: "600Mi"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
